### PR TITLE
Add the fix script

### PR DESCRIPTION
**Pull request by zklaus**
Converts 2d coordinates for latitude and longitude to their 1d versions if they are the same for all rows/columns.

### CODE REVIEW

**Comment by jonseddon** [comment]
@zklaus that looks good and the output files are passing PrePARE. I can spot a couple of issues in the output files:

1. according to point 5 in https://docs.google.com/document/d/1os9rZ11U0ajY7F8FWtgU4B49KcB59aFlBVGfLC4ahXs/edit#bookmark=id.syc4ep5duqyq then the coordinates should be output in the order given in the dimensions descriptor in the mip tables, e.g. for clt_Amon "longitude latitude time" and then clt last.
1. could you enable shuffle and deflation (at level 3) please.
1. could the time coordinate be unlimited.

The last two points are easy to do in Iris. We don't think that the first is possible in Iris though (but we have a request open to have this added for future work). I think that it may be necessary to use the netCDF library to do this.

Thanks,

Jon

**Comment by zklaus** [comment]
Thanks for the feedback! I addressed your points 2. and 3. With regards to 1., my reading of the reference you mention is a bit different: I always read this as a statement of the order of axes on the variable, ie about the fact that in the output of ncdump clt shows up as
```
variables:
        float clt(time, lat, lon) ;
```
and not as
```
variables:
        float clt(lat, lon, time) ;
```
or similar. As such, I believe we are in compliance here since the order essentially has to be read backwards, ie the cmip table says `longitude latitude time` which ends up in the files as `time lat lon`.

This is in agreement with all the other cmip data I have seen also from other groups. Hence, no change to iris necessary (at least from the point of view of cmip).

But you're mentioning of compression and shuffle brought something else to my attention: What do you think about the chunking? Now for 2d fields like `clt` the chunk comes out as a full time slice. That seems ok, though probably more than one timestep per chunk might be advantageous. But for 3d fields like `hus`, the chunking is (1, 10, 128, 256), ie 10 levels and 4 quadrants. Do you have an opinion on this?

**Comment by jvegreg** [comment]
> could the time coordinate be unlimited.

Is this a requirement for CMIP? It increases disk footprint for small files. Not really worrying for PRIMAVERA, as most files are big, but I  like to avoid unlimited dims when possible.

>But you're mentioning of compression and shuffle brought something else to my attention: What do you think about the chunking? Now for 2d fields like clt the chunk comes out as a full time slice. That seems ok, though probably more than one timestep per chunk might be advantageous. 
But for 3d fields like hus, the chunking is (1, 10, 128, 256), ie 10 levels and 4 quadrants. Do you have an opinion on this?

It heavily depends on the usage, so it is impossible to choose a way that will not harm any use case. 
Anyway, I think that for 3D atmos filed is quite common to extract a single level, so maybe we can use (1, 1, full, full) for the atmos?

**Review by jvegreg — APPROVED** [review]
Looks nice! I have a doubt. How much time the computation of the new lat lon coords take? If it is high enough, maybe you can change the code to work by-folder instead of by-file. Coordinates will then be computed once per folder and not once per file

**Comment by zklaus** [comment]
I think the time needed is negligible since it only extracts existing values from the more complicated layout. Going by directory (or doing some other form of caching) could be an option, but I went with @jonseddon's request to have a script that takes a single file and changes it in place.

Probably it will be fine, but let's keep it in mind if the performance is a problem, ok?

**Comment by jonseddon** [comment]
> or similar. As such, I believe we are in compliance here since the order essentially has to be read backwards, ie the cmip table says `longitude latitude time` which ends up in the files as `time lat lon`.

Does the backwards come from the "_(opposite the FORTRAN convention)_" in the documentation?

> But you're mentioning of compression and shuffle brought something else to my attention: What do you think about the chunking? Now for 2d fields like `clt` the chunk comes out as a full time slice. That seems ok, though probably more than one timestep per chunk might be advantageous. But for 3d fields like `hus`, the chunking is (1, 10, 128, 256), ie 10 levels and 4 quadrants. Do you have an opinion on this?

Chunking is tricky and depends on the usage pattern. Our summer student did some experiments and the results are at https://github.com/PRIMAVERA-H2020/primavera-viewer/wiki/Data-Storage-Methods#chunking-experiments. The Unidata Python code generally gave the most optimal performance across a variety of access patterns.

I guess that the ordering of the variables in the files isn't important. The ncdump output will look different to users but it shouldn't affect data access.

Sorry, it will have to work on a single file due to how the ESGF submission software was designed.

**Comment by zklaus** [comment]
> > or similar. As such, I believe we are in compliance here since the order essentially has to be read backwards, ie the cmip table says `longitude latitude time` which ends up in the files as `time lat lon`. 
> Does the backwards come from the "_(opposite the FORTRAN convention)_" in the documentation?

I am not quite sure, but to be honest, that document might just be wrong. It is a bit vague, but if read to imply the opposite order, it would certainly be in contrast to [CF-1.7, Section 2.4](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#dimensions) and the corresponding [COARDS](https://ferret.pmel.noaa.gov/Ferret/documentation/coards-netcdf-conventions) standard, as well as the absolute overwhelming majority (if not totality, I don't know a single counter example) of CMIP5 and CMIP6 data. So, I think we good :)

> > But you're mentioning of compression and shuffle brought something else to my attention: What do you think about the chunking? Now for 2d fields like `clt` the chunk comes out as a full time slice. That seems ok, though probably more than one timestep per chunk might be advantageous. But for 3d fields like `hus`, the chunking is (1, 10, 128, 256), ie 10 levels and 4 quadrants. Do you have an opinion on this?
> 
> Chunking is tricky and depends on the usage pattern. Our summer student did some experiments and the results are at https://github.com/PRIMAVERA-H2020/primavera-viewer/wiki/Data-Storage-Methods#chunking-experiments. The Unidata Python code generally gave the most optimal performance across a variety of access patterns.

Chunking definitely is an underappreciated topic. Until you play with it yourself and you realize that suddenly your code runs a hundred times faster without any change. The results of your summer student are also very interesting, but I don't quite understand the applied access patterns. Maybe it would be worthwhile to do a little project on that sometime?

Anyway, for now I propose the following three options to choose from since we all seem to be a bit unclear about what would actually be the best
- do nothing, ie let iris/dask decide
- chunk to one time slice, ie for 2d fields (1, N_lat, N_lon), for 3d fields (1, N_lev, N_lat, N_lon)
- chunk to 2d fields, ie for 2d fields (1, N_lat, N_lon), for 3d fields (1, 1, N_lat, N_lon)
 
> I guess that the ordering of the variables in the files isn't important. The ncdump output will look different to users but it shouldn't affect data access.

I completely agree.

> Sorry, it will have to work on a single file due to how the ESGF submission software was designed.

Well, that settles that :)

**Comment by jonseddon** [comment]
> Chunking definitely is an underappreciated topic. Until you play with it yourself and you realize that suddenly your code runs a hundred times faster without any change. The results of your summer student are also very interesting, but I don't quite understand the applied access patterns. Maybe it would be worthwhile to do a little project on that sometime?
> 
> Anyway, for now I propose the following three options to choose from since we all seem to be a bit unclear about what would actually be the best
> 
> * do nothing, ie let iris/dask decide
> * chunk to one time slice, ie for 2d fields (1, N_lat, N_lon), for 3d fields (1, N_lev, N_lat, N_lon)
> * chunk to 2d fields, ie for 2d fields (1, N_lat, N_lon), for 3d fields (1, 1, N_lat, N_lon)

A fourth option to add further confusion would be:

* Use the chunking sizes recommended by Unidata at https://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_choosing_shapes and https://www.unidata.ucar.edu/blog_content/data/2013/chunk_shape_3D.py, which give the best compromise for most access patterns. This will need extending for 4D data though.

We have a new student here for the whole year and so continuing the chunking work would be a good project for them.

**Comment by zklaus** [comment]
After reading more of the blog posts, I think this makes a lot of sense for the 3D case! Basically it optimizes the chunking such that both time-series of single points in space and slices of single points in time can be read with good performance.

Now how to extend that to 4D? In other words, what are the expected access patterns? Certainly reading time-series and reading individual levels, one at a time, are still common. Is it common to read all levels for one time step? There is a question about 4D data in the comments on the blog post and the answer of the author of the blog post and the original script is:

>Different chunk shapes are optimal for different patterns of access. For example, if you know that the data will primarily be accessed by fixed slices of the first dimension, optimal chunks would be in the shape 1 x 37 x 256 x 512 or a similar shape that fits within one physical disk block, such as 1 x 5 x 32 x 64, which for 4-byte values fits within a 64K disk block.
>
>If there is no most common access pattern, let D be the number of values you want in a chunk (preferably <= what one disk access can read), then let c = (D/(25256 * 37 * 256 * 512)) ^ (1/4), and use a chunk shape resulting from multiplying each dimension size by c and truncating to an integer.

So maybe it is best to heed his advice and follow that formula. That could also expedite this matter.

What do you think?

PS: @jonseddon, do we know anything about block sizes on esgf and/or jasmin disks?

**Pull request merged**
