### PR TITLE
Added chunking (closes #2)

### LINKED ISSUE #2: Improve chunking
For good performance it is important to have good chunking. We discussed some aspects in the first PR, but I decided to split it off to keep things tidy. A summary of the discussion in #1 follows.

### PR DESCRIPTION
**Pull request by zklaus**
This adds chunking following the methodology laid out in #2 using
resources from
https://www.unidata.ucar.edu/blogs/developer/entry/chunking_data_choosing_shapes
https://www.unidata.ucar.edu/blog_content/data/2013/chunk_shape_3D.py

Chunksize is set to 4MiB.

### CODE REVIEW

**Comment by zklaus** [comment]
@jonseddon, this implements chunking. I set the chunk size to 4MiB, which takes longer for the rechunking, but hopefully gives better performance. If you are happy with this, you can start work on the data and I will merge it into master.

**Comment by jonseddon** [comment]
@zklaus the unidata blog suggested that the chunk size should equal the file system's block size. It suggests that a 4KiB block size is common on desktop systems. Do you know what the block size is on the network group workspaces or on network storage at other sites?

**Comment by zklaus** [comment]
I don't. In fact I asked the same question in the old PR. But I did find [this](https://www.unidata.ucar.edu/software/netcdf/docs/netcdf_perf_chunking.html#default_chunking_4_1) where the netcdf guys say that a block size of 4MiB is reasonable for hpc platforms.

I would certainly be open to using 4KiB instead. Your call.

**Comment by jonseddon** [comment]
I've asked CEDA support about their chunk size and I've also asked about the size on various storage systems at my site. I'm not going to have a chance to convert the data until later next week and so there's no rush at the moment. Did you do any timing tests to see how long it took to run the code on typical files for different chunk sizes?

**Comment by zklaus** [comment]
I did. Namely on `hus_Amon_EC-Earth3P_highresSST-present_r1i1p1f1_gr_195001-195012.nc`. 

Here are some stats. Take the timing (measured with `time ./fix_lat...`)with a grain of salt since the filesystem also plays a role, but it seems indicative.

target chunk size|actual chunk size|time|chunking|file size
-|-|-|-|-
original|1.25M|original|(1, 10, 128, 256)|126M
4K|3.95K|0m13.848s|(1, 1, 22, 46)|80M
8K|8K|0m16.058s|(1, 1, 32, 64)|76M
1M|0.82M|0m38.744s|(4, 1, 164, 328)|77M
4M|3.69|1m41.466s|(9, 1, 232, 463)|81M

Of course the original is neither shuffled nor deflated so the file size in the first line doesn't compare to the other lines.

**Comment by jonseddon** [comment]
The Quobyte and Panasas storage at JASMIN both have a block size of 64 KiB. Our post-processing system isn't an HPC but uses a 4 MiB block size. I was also advised:

> I've believe netCDF chunk shape can also impact on performance if chunks are being compressed/deflated. If your normal access pattern doesn't align with your chunk shape, you end up doing many more inflate operations than you might have done otherwise.

Together with the results from our previous student (https://github.com/PRIMAVERA-H2020/primavera-viewer/wiki/Data-Storage-Methods) I think that a chunk size between 64 KiB and 1 MiB would be best. Your results and our students results both agree that the larger chunk sizes take longer to initially write. We have around 300 TiB of data to convert and so the time taken to run the code is important. 

Perhaps, could you also test the code on a larger (several GiB 3hr or 6hr file) to check that this will run ok on LOTUS?

**Comment by zklaus** [comment]
Sounds good. On which filesystem will you perform the final conversion? Probably on the group workspace?

**Comment by zklaus** [comment]
@jonseddon one more question: This started out as the lat lon fix, but do you want it to do rechunking, shuffling, and deflation even if the coordinates are already in order?

**Comment by jonseddon** [comment]
@zklaus 
> On which filesystem will you perform the final conversion?

The files are converted in place on the group workspace

> do you want it to do rechunking, shuffling, and deflation even if the coordinates are already in order?

If the coordinates are already in order then I will just publish the data directly with no changes made to the file. But I think that all of the EC-Earth3P and EC-Earth3P-HR files need fixing don't they?

**Comment by zklaus** [comment]
> But I think that all of the EC-Earth3P and EC-Earth3P-HR files need fixing don't they?

I think so too. Nevertheless I implemented a check in the script that skips any changes if the coordinates are already in order. Let's keep it that way.

**Comment by zklaus** [comment]
I added a command-line option to choose the chunksize and set the default to 64KiB. This is the smallest that you suggested which should be the fastest. Testing can continue, but I will merge this now because other aspects still need attention.

**Pull request merged**
